# Generated by Django 4.2.6 on 2023-10-05 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacao',
            old_name='dataPPublicacao',
            new_name='dataPublicacao',
        ),
    ]
